In [1]:
#importing data
from doughflow.data.make_dataset import load_raw_data, get_data_summary, rename_data, aggregate_daily_level

In [2]:
# loading data
df = load_raw_data("../data/raw")

new_df = rename_data(df)

new_df = aggregate_daily_level(new_df)

new_df

             date                item              type_of_item  quantity
0      2021-01-02            Baguette                   Regular         2
1      2021-01-02   Batard (football)                   Regular         2
2      2021-01-02        Butter Rolls                   Regular         7
3      2021-01-02  Cayuga Blue Cheese                   Regular         1
4      2021-01-02      Challah Kaiser                   Regular         3
...           ...                 ...                       ...       ...
35009  2025-10-30          Rolls/Buns               Kaiser Roll         2
35010  2025-10-30          Rolls/Buns  Kaiser Rolls (4 Or More)         2
35011  2025-10-30          Rolls/Buns    Kimmelweck (4 Or More)         2
35012  2025-10-30     Wholesale Items             Ciabatta Loaf        10
35013  2025-10-30     Wholesale Items              Levain 1200g         9

[35014 rows x 4 columns]

In [3]:
from doughflow.features.build_features import TemporalFeatureExtractor, ProductFeatureExtractor, LagFeatureExtractor
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('product', ProductFeatureExtractor(aggregation_level='item')),
    ('temporal', TemporalFeatureExtractor()),
    ('lag', LagFeatureExtractor(
        recent_lag_weeks=[1,2,3,4],
        yearly_lags=[1,2],
        fill_strategy= 'cascading'
    ))
])

df_cascading = pipeline.fit_transform(new_df)

df_cascading

,date,item,quantity,day_of_week,day_of_month,month,year,week_of_year,is_weekend,lag_1w_ago,lag_2w_ago,lag_3w_ago,lag_4w_ago,lag_1y_same_week,lag_2y_same_week,rolling_mean_7d,rolling_std_7d
0,2021-05-13,Croissant,42,3,13,5,2021,19,False,52.84,52.84,52.84,52.84,52.84,52.84,0.00,0.00
1,2021-05-14,Croissant,61,4,14,5,2021,19,False,42.00,42.00,42.00,42.00,52.84,52.84,42.00,0.00
2,2021-05-15,Croissant,100,5,15,5,2021,19,True,51.50,51.50,51.50,51.50,52.84,52.84,51.50,13.44
3,2021-05-16,Croissant,53,6,16,5,2021,19,True,67.67,67.67,67.67,67.67,52.84,52.84,67.67,29.57
4,2021-05-18,Croissant,21,1,18,5,2021,20,False,64.00,64.00,64.00,64.00,52.84,52.84,64.00,25.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1898,2025-10-23,Danish,14,3,23,10,2025,43,False,15.00,17.00,21.00,17.00,17.00,29.52,32.00,10.17
1899,2025-10-24,Danish,24,4,24,10,2025,43,False,29.00,25.00,24.00,24.00,37.00,36.00,30.43,12.09
1900,2025-10-25,Danish,42,5,25,10,2025,43,True,44.00,40.00,44.00,38.00,48.00,40.00,28.14,11.48
1901,2025-10-26,Danish,13,6,26,10,2025,43,True,31.00,40.00,10.00,10.00,35.00,21.00,28.43,11.84
1902,2025-10-30,Danish,16,3,30,10,2025,44,False,14.00,15.00,17.00,21.00,19.00,29.52,28.14,12.24

In [5]:
df_cascading.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1903 entries, 0 to 1902
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              1903 non-null   datetime64[ns]
 1   item              1903 non-null   object
 2   quantity          1903 non-null   int64
 3   day_of_week       1903 non-null   int32
 4   day_of_month      1903 non-null   int32
 5   month             1903 non-null   int32
 6   year              1903 non-null   int32
 7   week_of_year      1903 non-null   UInt32
 8   is_weekend        1903 non-null   bool
 9   lag_1w_ago        1903 non-null   float64
 10  lag_2w_ago        1903 non-null   float64
 11  lag_3w_ago        1903 non-null   float64
 12  lag_4w_ago        1903 non-null   float64
 13  lag_1y_same_week  1903 non-null   float64
 14  lag_2y_same_week  1903 non-null   float64
 15  rolling_mean_7d   1903 non-null   float64
 16  rolling_std_7d    1903 non-null   float64
dtypes: UInt32(1), bool(1), datetime64[ns](1), float64(8), int32(4), int64(1), object(1)
memory usage: 204.6+ KB